export const viewTitleMap: Record<string, string> = {
    'dashboard': 'داشبورد',
    'settings/companyDefinition': 'تعریف شرکت',
    'settings/defineCurrencies': 'تعریف ارزهای جهانی',
    'settings/fiscalYearDefinition': 'تعریف سال مالی',
    'settings/appearanceSettings': 'تنظیمات ظاهری',
    'settings/userManagement': 'تعریف کاربران',
    'settings/groupingManagement': 'مدیریت گروه بندی فرمها',
    'settings/backupAndRestore': 'پشتیبانی و بازیابی',
    'settings/groupPermissions': 'گروه کاربران و دسترسی‌ها',
    'deploymentManagement/deploymentStructureDefinition': 'تعریف ساختار استقرار',
    'orgStructure/orgChartSetup': 'تنظیم چارت سازمانی',
    'orgStructure/orgTaskSetup': 'تنظیم وظایف سازمانی',
    'orgStructure/personnelDefinition': 'تعریف پرسنل سازمانی',
    'orgStructure/personnelContractSettings': 'تنظیم قرارداد پرسنلی',
    'payroll/payrollFactorsDefinition': 'تعریف عوامل حقوق و دستمزد',
    'payroll/registerMonthlyWorklog': 'ثبت کارکرد ماهیانه',
    'payroll/monthlyPayrollCalculation': 'محاسبه حقوق ماهانه',
    'payroll/reports': 'گزارشات حقوق و دستمزد',
    'accounting/accountHeadDefinition': 'تعریف سرفصل',
    'accounting/detailedCodingSetup': 'تنظیمات کدینگ تفصیلی',
    'accounting/autoDocSetup': 'تنظیمات سند خودکار',
    'accounting/issueAccountingDocument': 'صدور سند حسابداری',
    'accounting/accountControl': 'کنترل سرفصلها',
    'accounting/ledgerReports': 'گزارش دفاتر',
    'receiveAndPay/defineBanks': 'تعریف بانکها',
    'receiveAndPay/defineCheckbooks': 'تعریف دسته چک‌ها',
    'receiveAndPay/defineCashboxes': 'تعریف صندوق',
    'receiveAndPay/definePOSTerminals': 'تعریف کارت خوان',
    'receiveAndPay/definePaymentGateways': 'تعریف درگاه پرداخت',
    'receiveAndPay/definePettyCash': 'تعریف تنخواه گردان',
    'receiveAndPay/registerTreasuryTransaction': 'ثبت تراکنش خزانه',
    'receiveAndPay/documentManagement': 'مدیریت اسناد خزانه',
    'receiveAndPay/cashAndBankReport': 'گزارش نقد و بانک',
    'supplyManagement/definePersons': 'تعریف اشخاص (تامین کنندگان)',
    'supplyManagement/defineServiceItem': 'تعریف خدمات',
    'supplyManagement/registerPurchaseInvoice': 'ثبت فاکتور خرید اقلام',
    'supplyManagement/registerPurchaseReturnInvoice': 'ثبت فاکتور برگشت خرید اقلام',
    'supplyManagement/registerAssetPurchaseInvoice': 'ثبت فاکتور خرید دارایی',
    'supplyManagement/registerAssetPurchaseReturnInvoice': 'ثبت فاکتور برگشت خرید دارایی',
    'supplyManagement/registerServicePurchaseInvoice': 'ثبت فاکتور خرید خدمات (هزینه)',
    'supplyManagement/defineWarehouse': 'تعریف انبار',
    'supplyManagement/defineMeasurementUnit': 'تعریف واحد اندازه گیری',
    'supplyManagement/definePurchaseItemGroup': 'تعریف گروه اقلام خریدنی',
    'supplyManagement/definePurchaseItem': 'تعریف اقلام خریدنی',
    'supplyManagement/registerWarehouseReceipt': 'ثبت رسید انبار',
    'supplyManagement/registerWarehouseReceiptReturn': 'ثبت برگشت رسید انبار',
    'supplyManagement/registerWarehouseIssue': 'ثبت خروج انبار',
    'supplyManagement/registerWarehouseIssueReturn': 'ثبت برگشت خروج انبار',
    'supplyManagement/registerWarehouseTransfer': 'ثبت انتقال بین انبارها',
    'supplyManagement/reports': 'گزارشات تامین',
    'productionManagement/defineWorkstations': 'تعریف ایستگاه کاری',
    'productionManagement/defineMachineryGroup': 'تعریف گروه ماشین آلات',
    'productionManagement/defineMachinery': 'تعریف ماشین آلات',
    'productionManagement/defineManufacturingProcess': 'تعریف فرآیند',
    'productionManagement/defineProductGroup': 'تعریف گروه محصولات',
    'productionManagement/defineProducts': 'تعریف محصولات',
    'productionManagement/registerProductManufacturing': 'ثبت سند تولید محصول',
    'productionManagement/reports': 'گزارشات تولید',
    'invoiceManagement/definePersons': 'تعریف مشتریان',
    'invoiceManagement/registerSalesInvoice': 'ثبت فاکتور فروش اقلام',
    'invoiceManagement/registerSalesReturnInvoice': 'ثبت فاکتور برگشت فروش اقلام',
    'invoiceManagement/registerAssetSalesInvoice': 'ثبت فاکتور فروش دارایی',
    'invoiceManagement/registerAssetSalesReturnInvoice': 'ثبت فاکتور برگشت فروش دارایی',
    'invoiceManagement/registerServiceSalesInvoice': 'ثبت فاکتور فروش خدمات (درآمد)',
    'invoiceManagement/reports': 'گزارشات فروش',
    'crm/salesTimeline': 'تایم لاین عملیاتی',
    'campaignManagement/defineCampaigns': 'مدیریت کمپین ها',
    'campaignManagement/defineCampaignAudience': 'تعریف مخاطبان کمپین',
    'campaignManagement/defineEmailTemplate': 'تعریف قالب ایمیل مارکتینگ',
    'campaignManagement/defineSmsTemplate': 'تعریف قالب SMS مارکتینگ',
    'campaignManagement/defineSocialTemplate': 'تعریف قالب سوشال مارکتینگ',
    'campaignManagement/reports': 'گزارشات کمپین',
    'opportunityManagement/registerOpportunity': 'مدیریت فرصت‌ها',
    'opportunityManagement/reports': 'گزارشات فرصت‌ها',
    'quotationManagement/registerQuotation': 'مدیریت پیش فاکتورها',
    'quotationManagement/reports': 'گزارشات پیش فاکتور',
    'assetManagement/defineAssetLocation': 'تعریف محل استقرار',
    'assetManagement/defineDepreciationMethod': 'تعریف روش استهلاک',
    'assetManagement/defineAsset': 'تعریف دارایی',
    'assetManagement/assetDeployment': 'استقرار دارایی',
    'assetManagement/assetDepreciation': 'استهلاک دارایی',
    'assetManagement/operations': 'عملیات جمع داری اموال',
    'assetManagement/reports': 'گزارشات جمع داری اموال',
    'budgeting/definitions': 'تعاریف بودجه ریزی',
    'budgeting/salesForecast': 'پیشبینی فروش',
    'budgeting/directMaterialPurchaseForecast': 'پیشبینی خرید مواد مستقیم',
    'budgeting/directLaborForecast': 'پیشبینی دستمزد مستقیم',
    'budgeting/otherIncomeExpenseForecast': 'پیشبینی سایر درآمدها و هزینه ها',
    'budgeting/salesTargetControl': 'کنترل اهداف فروش',
    'trendsManagement/defineTrend': 'تعریف روند',
    'trendsManagement/operations': 'عملیات روندها',
    'trendsManagement/reports': 'گزارشات روندها',
    'trendsManagement/personalSettings': 'تنظیمات شخصی',
};